### ISSUE TITLE
.js bouuuuh

### ISSUE THREAD

**Issue by xtekky** [Automized/Discord-Nitro-Promotion-Gen#1]

**Comment by Automized** [comment]
shush, you've never used async before today

**Comment by b6m** [comment]
real ( make it threaded and request based now )

**Comment by Pr0t0ns** [comment]
> real ( make it threaded and request based now )

It will be hard because of sig

**Comment by Automized** [comment]
> > real ( make it threaded and request based now )
> 
> It will be hard because of sig

yes, me and tekky are mid way reversing it

**Comment by b6m** [comment]
not hard, i alr made one yesterday lmao

**Comment by Automized** [comment]
> not hard, i alr made one yesterday lmao

Seem to be struggling with the signature.

**Comment by Pr0t0ns** [comment]
> > not hard, i alr made one yesterday lmao
> 
> Seem to be struggling with the signature.

it's easy it's a checksum just hash the route and payload with md5 if u need more info on how to do it use breakpoint's it literally shows u in the source how they create the checksum

**Comment by Automized** [comment]
I have already made it in request, the day I said I was struggling with signature lmao
